//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPADemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeTable
    {
        public int EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public string Email { get; set; }
        public string Project { get; set; }
        public Nullable<System.DateTime> DOJ { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
    }
}
